description: >-
  Andre LeBlanc is an engineering manager at Trusted Health, a Shopify Alum,
  a real estate investor with 13 units, and an amateur sailor with 1000nm.
jekyll_admin:
  homepage: "pages"
plugins:
  - jekyll-admin
  - jekyll-feed
theme: minima

title: AndreLeBlanc.me
author: Andre LeBlanc
email: blog@andreleblanc.me

github_username: andremleblanc
instagram_username: andremleblanc
linkedin_username: andremleblanc
